---
- name: install apache
  hosts: all
  become: yes
  tasks:
    - name: update Ubuntu packages 
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'    
    - name: install apache
      package:
        name: "{{ package_name }}"
        state: present    
    - name: start and enable apache
      service:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: install php packages 
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
    - name: restart apache2
      service:
        name: "{{ package_name }}"
        state: restarted